import { Roboto } from 'next/font/google'
import './globals.css'
import StoreProvider from './StoreProvider'

const roboto = Roboto({ subsets: ['latin'], weight: ['100', '300', '400', '500', '700', '900'] })

export const metadata = {
  title: '$MySlave',
  description: 'Generated by create JRS',
}

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="pt-br">
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <body className={roboto.className}>{children}</body>
      </html>
    </StoreProvider>
  )
}
